okred_job_employerprofile_main:
    pattern: /
    defaults:
        _controller: OkredJobBundle:Employer:responses

okred_job_employerprofile_view:
    pattern: /view
    defaults:
        _controller: OkredJobBundle:Employer:profile
