fos_user_registration_register:
    pattern: /
    defaults:
        _controller: FOSUserBundle:Registration:register

fos_user_registration_register:
    pattern: /check-email
    methods: [GET]
    defaults:
        _controller: FOSUserBundle:Registration:checkEmail

fos_user_registration_confirm:
    pattern: /confirm/{token}
    methods : [GET]
    defaults:
        _controller: FOSUserBundle:Registration:confirm

fos_user_registration_confirmed:
    pattern: /confirmed
    methods: [GET]
    defaults:
        _controller: FOSUserBundle:Registration:confirmed
