parameters:
#    okred_job.example.class: Okred\Bundle\JobBundle\Example

services:
#    okred_job.example:
#        class: %okred_job.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
