parameters:
#    okred_user.example.class: Okred\Bundle\UserBundle\Example

services:
#    okred_user.example:
#        class: %okred_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
